# Project: AgendaConsoleDevC++
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o menu/menu.o datasources/datasource.o utils/bubble_sort.o utils/clearScreen.o utils/stringCreate.o
LINKOBJ  = main.o menu/menu.o datasources/datasource.o utils/bubble_sort.o utils/clearScreen.o utils/stringCreate.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = AgendaConsoleDevC++.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

menu/menu.o: menu/menu.c
	$(CC) -c menu/menu.c -o menu/menu.o $(CFLAGS)

datasources/datasource.o: datasources/datasource.c
	$(CC) -c datasources/datasource.c -o datasources/datasource.o $(CFLAGS)

utils/bubble_sort.o: utils/bubble_sort.c
	$(CC) -c utils/bubble_sort.c -o utils/bubble_sort.o $(CFLAGS)

utils/clearScreen.o: utils/clearScreen.c
	$(CC) -c utils/clearScreen.c -o utils/clearScreen.o $(CFLAGS)

utils/stringCreate.o: utils/stringCreate.c
	$(CC) -c utils/stringCreate.c -o utils/stringCreate.o $(CFLAGS)
