# Project: AgendaConsoleDevC++
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o menu/menu.o datasources/datasource.o utils/bubble_sort.o utils/clearScreen.o utils/stringCreate.o
LINKOBJ  = main.o menu/menu.o datasources/datasource.o utils/bubble_sort.o utils/clearScreen.o utils/stringCreate.o
LIBS     = -L"M:/Dev-Cpp/MinGW32/lib" -L"M:/Dev-Cpp/MinGW32/mingw32/lib" -L"C:/GLUT" -static-libstdc++ -static-libgcc -g3
INCS     = -I"M:/Dev-Cpp/MinGW32/include" -I"M:/Dev-Cpp/MinGW32/mingw32/include" -I"M:/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"C:/GLUT"
CXXINCS  = -I"M:/Dev-Cpp/MinGW32/include" -I"M:/Dev-Cpp/MinGW32/mingw32/include" -I"M:/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"M:/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++" -I"C:/GLUT"
BIN      = AgendaConsoleDevC++.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

menu/menu.o: menu/menu.c
	$(CC) -c menu/menu.c -o menu/menu.o $(CFLAGS)

datasources/datasource.o: datasources/datasource.c
	$(CC) -c datasources/datasource.c -o datasources/datasource.o $(CFLAGS)

utils/bubble_sort.o: utils/bubble_sort.c
	$(CC) -c utils/bubble_sort.c -o utils/bubble_sort.o $(CFLAGS)

utils/clearScreen.o: utils/clearScreen.c
	$(CC) -c utils/clearScreen.c -o utils/clearScreen.o $(CFLAGS)

utils/stringCreate.o: utils/stringCreate.c
	$(CC) -c utils/stringCreate.c -o utils/stringCreate.o $(CFLAGS)
